name: MBTFv2_SR_x2
model_type: SRModel
scale: 2
num_gpu: 1
manual_seed: 42

datasets:
  train:
    name: MySR_train
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_HR
    dataroot_lq: datasets/DIV2K/DIV2K_LR_bicubic/x2
    filename_tmpl: '{}x2'
    io_backend: {type: disk}
    gt_size: 128           # Colab T4 thân thiện; tăng nếu VRAM dư
    use_hflip: true
    use_rot: true
    scale: 2               # Rất quan trọng để crop khớp LR/HR

val_0:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/HR
    dataroot_lq: datasets/Set5/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk
  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/HR
    dataroot_lq: datasets/Set14/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk


network_g:
  type: MBTaylorFormerV2SR
  scale: 2
  in_ch: 3
  out_ch: 3
  dim: 180         # chỉnh theo VRAM; 160/192 đều OK

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  optim_g: {type: Adam, lr: 2e-4, betas: [0.9, 0.999]}
  scheduler:
    type: MultiStepLR
    milestones: [200000, 300000]
    gamma: 0.5
  total_iter: 400000
  warmup_iter: -1

  # Mixed precision giúp tiết kiệm VRAM Colab
  use_amp: true

  # EMA giúp ổn định training
  ema: {enable: true, ema_decay: 0.999}

  # Loss: L1 + Perceptual
  pixel_opt: {type: L1Loss, loss_weight: 1.0, reduction: mean}
  perceptual_opt:
    type: PerceptualLoss
    layer_weights: {'conv5_4': 1.0}
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0.0

val:
  val_freq: 5000
  save_img: false
  metrics:
    psnr: {type: calculate_psnr, crop_border: 2, test_y_channel: true}
    ssim: {type: calculate_ssim, crop_border: 2, test_y_channel: true}

logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true

# experiments/ (mặc định)
dist_params:
  backend: nccl
  port: 29500
